//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BililiveRecorder.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BililiveRecorder.WPF.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 联系方式 的本地化字符串。
        /// </summary>
        public static string About_Contact {
            get {
                return ResourceManager.GetString("About_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权所有 的本地化字符串。
        /// </summary>
        public static string About_Copyright {
            get {
                return ResourceManager.GetString("About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用的库 的本地化字符串。
        /// </summary>
        public static string About_LibrariesUsed {
            get {
                return ResourceManager.GetString("About_LibrariesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件为免费软件。
        ///本软件为开源软件，使用 GNU通用公共许可证第三版 （GPLv3） 授权。 的本地化字符串。
        /// </summary>
        public static string About_License {
            get {
                return ResourceManager.GetString("About_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B站录播姬 的本地化字符串。
        /// </summary>
        public static string About_Name {
            get {
                return ResourceManager.GetString("About_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目首页 的本地化字符串。
        /// </summary>
        public static string About_Project {
            get {
                return ResourceManager.GetString("About_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译者 的本地化字符串。
        /// </summary>
        public static string About_Translator {
            get {
                return ResourceManager.GetString("About_Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 {0} 的本地化字符串。
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方网站 的本地化字符串。
        /// </summary>
        public static string About_Website {
            get {
                return ResourceManager.GetString("About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string AddRoomCard_ConfirmButton {
            get {
                return ResourceManager.GetString("AddRoomCard_ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号或房间链接 的本地化字符串。
        /// </summary>
        public static string AddRoomCard_PlaceholderText {
            get {
                return ResourceManager.GetString("AddRoomCard_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 14 的本地化字符串。
        /// </summary>
        public static string AddRoomCard_PlaceholderText_FontSize {
            get {
                return ResourceManager.GetString("AddRoomCard_PlaceholderText_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加房间 的本地化字符串。
        /// </summary>
        public static string AddRoomCard_Title {
            get {
                return ResourceManager.GetString("AddRoomCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知道了 的本地化字符串。
        /// </summary>
        public static string AddRoomFailedDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这个直播间已经被添加过了 的本地化字符串。
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_Duplicate {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入B站直播房间号或直播间链接 的本地化字符串。
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_InvalidInput {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号不能是负数 的本地化字符串。
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_RoomIdNegative {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_RoomIdNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号不能是 0 的本地化字符串。
        /// </summary>
        public static string AddRoomFailedDialog_ErrorText_RoomIdZero {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_ErrorText_RoomIdZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加房间失败 的本地化字符串。
        /// </summary>
        public static string AddRoomFailedDialog_Title {
            get {
                return ResourceManager.GetString("AddRoomFailedDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告获取失败 的本地化字符串。
        /// </summary>
        public static string AnnouncementPage_FetchFailed {
            get {
                return ResourceManager.GetString("AnnouncementPage_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新公告内容 的本地化字符串。
        /// </summary>
        public static string AnnouncementPage_RefreshButton {
            get {
                return ResourceManager.GetString("AnnouncementPage_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出吗？ 的本地化字符串。
        /// </summary>
        public static string CloseWindowConfirmDialog_Title {
            get {
                return ResourceManager.GetString("CloseWindowConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除这个直播间吗？ 的本地化字符串。
        /// </summary>
        public static string DeleteRoomConfirmDialog_Title {
            get {
                return ResourceManager.GetString("DeleteRoomConfirmDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Global_Close {
            get {
                return ResourceManager.GetString("Global_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Global_Confirm {
            get {
                return ResourceManager.GetString("Global_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Global_Copy {
            get {
                return ResourceManager.GetString("Global_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Global_Quit {
            get {
                return ResourceManager.GetString("Global_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右键点击可以复制单行日志 的本地化字符串。
        /// </summary>
        public static string LogPage_RightClickCopyToolTip {
            get {
                return ResourceManager.GetString("LogPage_RightClickCopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 级别 的本地化字符串。
        /// </summary>
        public static string LogPanel_Header_Level {
            get {
                return ResourceManager.GetString("LogPanel_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string LogPanel_Header_Message {
            get {
                return ResourceManager.GetString("LogPanel_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号 的本地化字符串。
        /// </summary>
        public static string LogPanel_Header_RoomId {
            get {
                return ResourceManager.GetString("LogPanel_Header_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string LogPanel_Header_Timestamp {
            get {
                return ResourceManager.GetString("LogPanel_Header_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string LogPanel_Level_Debug {
            get {
                return ResourceManager.GetString("LogPanel_Level_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string LogPanel_Level_Error {
            get {
                return ResourceManager.GetString("LogPanel_Level_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 致命 的本地化字符串。
        /// </summary>
        public static string LogPanel_Level_Fatal {
            get {
                return ResourceManager.GetString("LogPanel_Level_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string LogPanel_Level_Information {
            get {
                return ResourceManager.GetString("LogPanel_Level_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string LogPanel_Level_Verbose {
            get {
                return ResourceManager.GetString("LogPanel_Level_Verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string LogPanel_Level_Warning {
            get {
                return ResourceManager.GetString("LogPanel_Level_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回放剪辑（正在处理中的数量） 的本地化字符串。
        /// </summary>
        public static string RoomCard_ClipButton_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_ClipButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除房间 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_Delete {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不自动录制 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_DisableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_DisableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动录制 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_EnableAutoRecord {
            get {
                return ResourceManager.GetString("RoomCard_Menu_EnableAutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开直播间页面 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_OpenInBrowser {
            get {
                return ResourceManager.GetString("RoomCard_Menu_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新直播间信息 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_RefreshInfo {
            get {
                return ResourceManager.GetString("RoomCard_Menu_RefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间设置 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_Settings {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始录制 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_StartRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止录制 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_StopRecording {
            get {
                return ResourceManager.GetString("RoomCard_Menu_StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string RoomCard_Menu_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切割录制输出文件 的本地化字符串。
        /// </summary>
        public static string RoomCard_SplitButton_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_SplitButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次直播不再自动录制，结束直播时恢复 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_AutoRecordForThisSessionDisabled_Tooltip {
            get {
                return ResourceManager.GetString("RoomCard_Status_AutoRecordForThisSessionDisabled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕连接被断开
        ///录播姬通过弹幕服务器接收开播状态推送 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_DanmakuConnectionTooltip_False {
            get {
                return ResourceManager.GetString("RoomCard_Status_DanmakuConnectionTooltip_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接弹幕服务器
        ///实时接收开播状态和其他数据 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_DanmakuConnectionTooltip_True {
            get {
                return ResourceManager.GetString("RoomCard_Status_DanmakuConnectionTooltip_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未开播 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_LiveStatusTooltip_False {
            get {
                return ResourceManager.GetString("RoomCard_Status_LiveStatusTooltip_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直播中 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_LiveStatusTooltip_True {
            get {
                return ResourceManager.GetString("RoomCard_Status_LiveStatusTooltip_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控中 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_Monitoring {
            get {
                return ResourceManager.GetString("RoomCard_Status_Monitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制中 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_Recording {
            get {
                return ResourceManager.GetString("RoomCard_Status_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前文件时长: {0:g} 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_CurrentFileDuration {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_CurrentFileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这里显示的是录制的速度与主播直播速度的比
        ///正常应为接近 100% 颜色显示为绿色 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_Description {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无统计数据 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_NoData {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制经过时间: {0:g} 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SessionDuration {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:F2} Mbps 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SpeedInMbps {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SpeedInMbps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前速度比： {0:P2} 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_SpeedInPercentage {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_SpeedInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件时长: {0:g} 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_TotalFileDuration {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_TotalFileDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收数据量 {0} 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_TotalnputBytes {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_TotalnputBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入数据量 {0} 的本地化字符串。
        /// </summary>
        public static string RoomCard_Status_SpeedIndicator_TotalOutputBytes {
            get {
                return ResourceManager.GetString("RoomCard_Status_SpeedIndicator_TotalOutputBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消自动录制全部房间 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_DisableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动录制全部房间 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_AutoRecord_EnableAll {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_AutoRecord_EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_File {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改工作目录（会重启） 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_File_ChangeWorkPath {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_ChangeWorkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开工作目录 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_File_OpenWorkDirectory {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_OpenWorkDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_File_SaveConfig {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示日志文件 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_File_ShowLogFilesInExplorer {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_File_ShowLogFilesInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Links {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常见问题 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Links_FAQ {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Links_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赞助 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Links_Sponsor {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Links_Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Links_Website {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Links_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不排序 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Sort_Default {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按房间号排序 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Sort_RoomId {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_RoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按录制状态排序 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_Sort_Status {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_Sort_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_View {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示日志 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_View_ShowLogCheckBox {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_View_ShowLogCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示直播间标题和分区 的本地化字符串。
        /// </summary>
        public static string RoomListPage_Menu_View_ShowTitleAndAreaCheckBox {
            get {
                return ResourceManager.GetString("RoomListPage_Menu_View_ShowTitleAndAreaCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        public static string RootPage_NavigationViewItem_AdvancedSettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AdvancedSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告 的本地化字符串。
        /// </summary>
        public static string RootPage_NavigationViewItem_AnnouncementPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_AnnouncementPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string RootPage_NavigationViewItem_LogPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_LogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间列表 的本地化字符串。
        /// </summary>
        public static string RootPage_NavigationViewItem_RoomListPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_RoomListPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string RootPage_NavigationViewItem_SettingsPage {
            get {
                return ResourceManager.GetString("RootPage_NavigationViewItem_SettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        public static string Settings_AdvancedPage_Title {
            get {
                return ResourceManager.GetString("Settings_AdvancedPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：一般用户通常不需要也不应该修改这里的设置项。
        ///对 Timing 的修改可能会导致被B站服务器屏蔽、不能及时开始录制等问题。 的本地化字符串。
        /// </summary>
        public static string Settings_AdvancedPage_Warning {
            get {
                return ResourceManager.GetString("Settings_AdvancedPage_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发写硬盘所需弹幕个数 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_FlushInterval {
            get {
                return ResourceManager.GetString("Settings_Danmaku_FlushInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕录制 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_Title {
            get {
                return ResourceManager.GetString("Settings_Danmaku_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存弹幕 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Enabled {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 送礼信息 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Gift {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 舰长购买 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Guard {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 弹幕原始数据 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_Raw {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 SuperChat 的本地化字符串。
        /// </summary>
        public static string Settings_Danmaku_ToggleSwitch_SuperChat {
            get {
                return ResourceManager.GetString("Settings_Danmaku_ToggleSwitch_SuperChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪辑文件名格式 的本地化字符串。
        /// </summary>
        public static string Settings_FileName_Clip {
            get {
                return ResourceManager.GetString("Settings_FileName_Clip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说明 的本地化字符串。
        /// </summary>
        public static string Settings_FileName_Description_Text {
            get {
                return ResourceManager.GetString("Settings_FileName_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名变量说明
        ///
        ///日期: {date}
        ///时间: {time}
        ///房间号: {roomid}
        ///标题: {title}
        ///主播名: {name}
        ///大分区: {parea}
        ///子分区: {area}
        ///随机数字: {random}
        ///
        ///所有大括号均为英文半角括号
        ///只支持 FLV 格式 的本地化字符串。
        /// </summary>
        public static string Settings_FileName_Description_ToolTip {
            get {
                return ResourceManager.GetString("Settings_FileName_Description_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制文件名格式 的本地化字符串。
        /// </summary>
        public static string Settings_FileName_Record {
            get {
                return ResourceManager.GetString("Settings_FileName_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string Settings_FileName_Title {
            get {
                return ResourceManager.GetString("Settings_FileName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪辑将来时长 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_Clip_FutureDuration_Left {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_FutureDuration_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_Clip_FutureDuration_Right {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_FutureDuration_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪辑过去时长 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_Clip_PastDuration_Left {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_PastDuration_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_Clip_PastDuration_Right {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Clip_PastDuration_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始数据模式 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_RadioButton_RawData {
            get {
                return ResourceManager.GetString("Settings_RecordMode_RadioButton_RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准模式 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_RadioButton_Standard {
            get {
                return ResourceManager.GetString("Settings_RecordMode_RadioButton_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制模式 的本地化字符串。
        /// </summary>
        public static string Settings_RecordMode_Title {
            get {
                return ResourceManager.GetString("Settings_RecordMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings_SettingsPage_Title {
            get {
                return ResourceManager.GetString("Settings_SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据文件大小自动分段 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_RadioButton_BySize {
            get {
                return ResourceManager.GetString("Settings_Splitting_RadioButton_BySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据视频时间自动分段 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_RadioButton_ByTime {
            get {
                return ResourceManager.GetString("Settings_Splitting_RadioButton_ByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不自动分段 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_RadioButton_Disabled {
            get {
                return ResourceManager.GetString("Settings_Splitting_RadioButton_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_TextBox_Left {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为一个文件 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_TextBox_Right {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MiB 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_TextBox_SizeUnit {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_SizeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_TextBox_TimeUnit {
            get {
                return ResourceManager.GetString("Settings_Splitting_TextBox_TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动分段 的本地化字符串。
        /// </summary>
        public static string Settings_Splitting_Title {
            get {
                return ResourceManager.GetString("Settings_Splitting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook 地址，一行一个 的本地化字符串。
        /// </summary>
        public static string Settings_Webhook_Address {
            get {
                return ResourceManager.GetString("Settings_Webhook_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webhook 的本地化字符串。
        /// </summary>
        public static string Settings_Webhook_Title {
            get {
                return ResourceManager.GetString("Settings_Webhook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string SettingWithDefault_Default {
            get {
                return ResourceManager.GetString("SettingWithDefault_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开主界面 的本地化字符串。
        /// </summary>
        public static string TaskbarIconControl_MenuItem_OpenMainWindow {
            get {
                return ResourceManager.GetString("TaskbarIconControl_MenuItem_OpenMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录播姬已最小化到托盘，左键单击图标恢复界面 的本地化字符串。
        /// </summary>
        public static string TaskbarIconControl_MinimizedNotification {
            get {
                return ResourceManager.GetString("TaskbarIconControl_MinimizedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B站录播姬 的本地化字符串。
        /// </summary>
        public static string TaskbarIconControl_Title {
            get {
                return ResourceManager.GetString("TaskbarIconControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件内存在录播姬无法自动修复的问题
        ///请点击 修复失败？ 按钮并反馈本问题 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_ContainsUnrepairable {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_ContainsUnrepairable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要修复 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_FixNeeded {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_FixNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无需修复 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_FixNotNeeded {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_FixNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辨率、解码问题 {0} 处 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeDecodingHeader {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeDecodingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他问题 {0} 处 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeOther {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复片段 {0} 处 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeRepeatingData {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeRepeatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间戳跳变问题 {0} 处 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampJump {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间戳错位问题 {0} 处 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampOffset {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeTimestampOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法修复的问题 {0} 处 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_IssueTypeUnrepairable {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_IssueTypeUnrepairable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注：不分析也可以进行修复操作 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_NoDataNote {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_NoDataNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击分析按钮开始分析 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_NoDataTitle {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_NoDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复将会输出 {0} 个文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_OutputFileCount {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_OutputFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音频 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Audio {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均FPS {0:F2} 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_AvgFPS {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_AvgFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅供参考，有问题的文件的统计可能不准确 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Disclaimer {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧数量 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_FrameCount {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧数量 {0} 个 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_FrameCountTemplate {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_FrameCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧时长 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_FrameDuration {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_FrameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计数据 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_AnalyzeResult_Stats_Video {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_AnalyzeResult_Stats_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分析 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_ButtonAnalyze {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_ButtonFix {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复失败？ 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_ButtonNotFixed {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonNotFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择... 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_ButtonSelectInput {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_ButtonSelectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了错误 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_Error {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取文件失败 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_InputIOError {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_InputIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入不是FLV文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_NotFlvFile {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_NotFlvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_OK {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入文件失败 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_OutputIOError {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_OutputIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的FLV数据类型 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Error_Type_UnknownFlvTagType {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Error_Type_UnknownFlvTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FLV 文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_InputPathPlaceholder {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_InputPathPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出原始分析数据 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_NotFixed_ButtonExportData {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_NotFixed_ButtonExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果修复出错、或在修复后依旧有问题
        ///请发邮件到 rec@danmuji.org 反馈。
        ///在邮件内附上此处导出的分析数据，
        ///并尽量详细描述视频的问题、所使用的录播姬版本。
        ///请分析未经修复的原始文件，而不是录播姬修复后的文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_NotFixed_Description {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_NotFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多信息请点击这里 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_NotFixed_LearnMore {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_NotFixed_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择视频文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_SelectInputDialog_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_SelectInputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择保存位置 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_SelectOutputDialog_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_SelectOutputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录播修复 的本地化字符串。
        /// </summary>
        public static string Toolbox_AutoFix_Title {
            get {
                return ResourceManager.GetString("Toolbox_AutoFix_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Button_AddFile {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Button_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Button_Merge {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Button_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Button_Remove {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最少需要 2 个文件才能合并 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Error_AtLeastTwo {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Error_AtLeastTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要合并的 XML 弹幕文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("Toolbox_Merge_OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击下方添加按钮，或拖动文件到此界面 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Tip {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕合并 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Title {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹幕 XML 文件合并 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_Title_Long {
            get {
                return ResourceManager.GetString("Toolbox_Merge_Title_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML 弹幕文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_Merge_XmlDanmakuFiles {
            get {
                return ResourceManager.GetString("Toolbox_Merge_XmlDanmakuFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择需要转封装的 FLV 文件 的本地化字符串。
        /// </summary>
        public static string Toolbox_Remux_OpenFileTitle {
            get {
                return ResourceManager.GetString("Toolbox_Remux_OpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 MP4 文件保存位置 的本地化字符串。
        /// </summary>
        public static string Toolbox_Remux_SaveFileTitle {
            get {
                return ResourceManager.GetString("Toolbox_Remux_SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转封装 的本地化字符串。
        /// </summary>
        public static string Toolbox_Remux_Title {
            get {
                return ResourceManager.GetString("Toolbox_Remux_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具箱 的本地化字符串。
        /// </summary>
        public static string Toolbox_Title {
            get {
                return ResourceManager.GetString("Toolbox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B站录播姬 {0} 的本地化字符串。
        /// </summary>
        public static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览... 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Browse {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件加载失败 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Error_FailedToLoadConfig {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_FailedToLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Error_None {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录已有其他文件 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Error_PathContainsFiles {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_PathContainsFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录不存在 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Error_PathDoesNotExist {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_PathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持该路径 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Error_PathNotSupported {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_PathNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生了未知错误 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Error_UnknownError {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Error_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不再询问 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_SkipAsking {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_SkipAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择工作目录 的本地化字符串。
        /// </summary>
        public static string WorkDirectorySelector_Title {
            get {
                return ResourceManager.GetString("WorkDirectorySelector_Title", resourceCulture);
            }
        }
    }
}
