apiVersion: apps/v1
kind: Deployment
  name: brec
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brec
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: brec
    spec:
      containers:
      - env:
        - name: BREC_ROOM_ID_LIST
          value: "23140417"
        image: registry-vpc.cn-shanghai.aliyuncs.com/maireo95/brec:cli-1.4.3
        imagePullPolicy: IfNotPresent
        name: brec
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /rec
          name: rec
        - mountPath: /app/logs
          name: logs
      - image: registry-vpc.cn-shanghai.aliyuncs.com/maireo95/dotnet-sidecar-monitor:6.0
        imagePullPolicy: IfNotPresent
        name: toolbox
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      shareProcessNamespace: true
      volumes:
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /mnt/oss/yukiko-live-recording/brec
          type: ""
        name: rec
      - hostPath:
          path: /tmp/brec/
          type: ""
        name: logs