apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: brec
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brec
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: brec
    spec:
      containers:
      - env:
        - name: BREC_ROOM_ID_LIST
          value: "23140417"
        image: registry-vpc.cn-shanghai.aliyuncs.com/maireo95/brec:cli-1.4.1
        imagePullPolicy: IfNotPresent
        name: brec
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /rec
          name: rec
        - mountPath: /app/logs
          name: logs
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /mnt/oss/yukiko-live-recording/brec
        name: rec
      - hostPath:
          path: /tmp/brec/
        name: logs
